spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dungeons
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #naming.implicit-strategy: ...
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
