version: '3.8'
services:
  local-database:
    image: "postgres:14.0"
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  dungeons-app:
    build:
      context: ../
    ports:
      - "8080:8080"
    depends_on:
      - local-database