version: '3.8'
services:
  local-database:
    image: "postgres:14.0"
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg-14-dungeons-vol:/var/lib/postgresql/data/
volumes:
  pg-14-dungeons-vol: {}
